// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlkkjojkaoniwhgdxelh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsa2tqb2prYW9uaXdoZ2R4ZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjE4NjUsImV4cCI6MjA2MjA5Nzg2NX0.vbR2omz7_PSaiAy5geCmM-NaXnmB6jaCXXac3JXlXjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);